/* eslint-disable */
// THIS FILE IS AUTO-GENERATED.
// Source: glossary/glossary.csv
// Generated by: scripts/generate-glossary.ts

import type { GlossaryItem } from './index';

export const GlossaryTermsSource: GlossaryItem[] = [
  {
    "letter": "A",
    "term": "Access to Infrastructure",
    "tag": "Risk Component",
    "definitions": {
      "short": "A measure of community proximity to critical physical infrastructure like roads, hospitals, railways, and Healthcare shelters",
      "long": "Evaluates connectivity of populations to services essential during and after disaster. Poor access amplifies vulnerability and slows recovery."
    },
    "details": {
      "ids_drr": "Evaluates proximity to roads, rail, hospitals, and shelters (Schools) at the revenue circle level. This layer feeds into the vulnerability score by identifying communities that would be cut off during floods.",
      "where_seen": "OpenStreetMap road data, NHM facility registers, PMGSY rural roads data, Census 2011 village amenities",
      "why_it_matters": "Road submergence during floods frequently cuts off communities. Poor infrastructure access disproportionately harms even moderate-hazard areas."
    }
  },
  {
    "letter": "D",
    "term": "DEM",
    "tag": "Data Source",
    "definitions": {
      "short": "Digital Elevation Model is a raster grid of bare-earth surface elevations",
      "long": "Foundation for all topographic flood analysis. Used to calculate slope, identify low-lying zones, derive drainage networks, compute TWI (Topographic Wetness Index), and model flood accumulation"
    },
    "details": {
      "ids_drr": "NASA DEM (30m) is a core input for Flood Hazard scoring. Elevation and slope derived from DEM identify District/Subdistrict and Revenue circlein low-lying flood-susceptible valley terrain. It is one of the main hazard data indicator.",
      "where_seen": "NASA Earth Data,USGS",
      "why_it_matters": "Elevation is the most powerful predictor of flood susceptibility. Low-elevation floodplains are structurally flood-prone regardless of embankments."
    }
  },
  {
    "letter": "D",
    "term": "Demographic Vulnerability",
    "tag": "Risk Component",
    "definitions": {
      "short": "The degree to which a population's social and demographic characteristics increase susceptibility to a hazard harm",
      "long": "Examines who the at-risk population is gender, age, economic deprivation and access to basic services. Populations with more women, elderly, deprived, or those lacking WASH (Water, Sanitation and Hygeine)  face greater harm."
    },
    "details": {
      "ids_drr": "Measures census indicators per District/Subdistrict/Revenue Ciircle: total population, sex ratio households without safe drinking water, and households without sanitation to undertsand who is more vulnerable to a flood related disater",
      "where_seen": "Census of India 2011 primary census abstract, SECC 2011 deprivation data, NFHS-5 district health indicators",
      "why_it_matters": "Reveals who bears the greatest burden. Poor WASH access amplifies flood health impacts through waterborne disease disproportionately affecting deprived communities."
    }
  },
  {
    "letter": "D",
    "term": "DRIMS",
    "tag": "Operational",
    "definitions": {
      "short": "Flood Reporting and Information Management System by  ASDMA for tracking flood damage across Assam during flood seasons",
      "long": "Primary operational data system for ASDMA to collect and publish daily flood situation reports during monsoon. Data covers population affected, houses damaged, livestock lost, crop inundated, and relief status."
    },
    "details": {
      "ids_drr": "DRIMS data forms a key component of IDS-DRR's past damages dataset. Provides the historical record of flood impacts at revenue circle level used to calibrate hazard scores.",
      "where_seen": "ASDMA website, daily monsoon situation reports, annual flood reports, IDS-DRR source dataset",
      "why_it_matters": "One of the few sub-district flood damage datasets systematically maintained in India. Its longitudinal record enables trend analysis and model validation."
    }
  },
  {
    "letter": "E",
    "term": "Embankment",
    "tag": "Risk Component",
    "definitions": {
      "short": "Earthen or concrete flood protection structures built along riverbanks to prevent floodwater from entering inhabited or agricultural land",
      "long": "Linear flood protection bunds along rivers.Their condition directly determines whether a flood event becomes a catastrophe."
    },
    "details": {
      "ids_drr": "Incorporates embankment condition and breach data in the loss and damages layer.",
      "where_seen": "Water Resources Department inspection records,SDMA flood damage reports, state budget allocations, procurement data",
      "why_it_matters": "Embankment breaches are the single most common cause of sudden large-scale inundation in certain geographies . A single breach can submerge dozens of villages overnight."
    }
  },
  {
    "letter": "E",
    "term": "Exposure",
    "tag": "data",
    "definitions": {
      "short": "The people property and assets located in hazard-prone areas",
      "long": "Exposure refers to what or who is present in places where hazardous events might occur. This includes population counts, buildings, infrastructure, agricultural land, and economic activities in at-risk zones."
    },
    "details": {
      "ids_drr": "IDS-DRR maps exposure using census data, satellite imagery, infrastructure databases, and economic activity records to show exactly what could be affected by different hazard scenarios.",
      "where_seen": "Exposure maps showing population density in risk zones, asset inventories, infrastructure overlays, and economic impact projections",
      "why_it_matters": "Understanding exposure helps quantify potential losses and prioritize protection measures. Reducing exposure through land-use planning or relocation is one of the most effective ways to reduce disaster risk."
    },
    "contexts": {
      "policy": "Used to determine land-use planning restrictions and relocation programs",
      "model": "Models predict population exposure based on historical hazard data, socioeconomic indicators, and climate projections to anticipate future risks."
    },
    "disaster_differences": [
      {
        "disaster_type": "Flood Exposure",
        "difference": "Based on population/assets in flood plains, near rivers, or low-lying coastal areas"
      },
      {
        "disaster_type": "Heat Exposure",
        "difference": "Based on population in areas with high temperatures, poor ventilation, or limited cooling"
      },
      {
        "disaster_type": "Cyclone Exposure",
        "difference": "Based on population/assets in coastal zones within cyclone-prone regions"
      }
    ],
    "related_terms": [
      "risk",
      "hazard",
      "vulnerability"
    ],
    "common_misinterpretation": "High exposure doesn't mean high risk if those exposed are well-protected or the hazard is unlikely"
  },
  {
    "letter": "G",
    "term": "Government Response",
    "tag": "Risk Component",
    "definitions": {
      "short": "The capacity of government institutions to prepare for, respond to, and recover from flood events",
      "long": "Measures how effectively public systems reduce harm before, during, and after an hazard event ncluding  relief infrastructure, procurement efficiency, and recovery expenditure."
    },
    "details": {
      "ids_drr": "Incorporates public procurement and fiscal data from the state tender portal and SECC Meetings  measure whether money for flood management is being spent effectively and on time.",
      "where_seen": "state budget documents, SDMA flood reports, Open Contracting procurement data, Finance Department expenditure records, SECC meetings",
      "why_it_matters": "Even high-hazard areas can have lower net risk with strong government response. Weak procurement amplifies disaster impacts."
    }
  },
  {
    "letter": "H",
    "term": "Hazard",
    "tag": "Risk Component",
    "definitions": {
      "short": "A potentially damaging natural event that may cause loss of life or property",
      "long": "A process, phenomenon or human activity that may cause loss of life, injury or other health impacts, property damage, social and economic disruption or environmental degradation."
    },
    "details": {
      "ids_drr": "Calculates a Flood Hazard Score per revenue circle/District/Subsditrict  using satellite-derived flood extent data, historical inundation records, and hydro-meteorological indicators.",
      "where_seen": "Flood hazard maps, inundation layers, SDMA early warning bulletins, IMD rainfall alerts, CWC flood forecasting data",
      "why_it_matters": "Hazard assessment shows where and how severely floods strike. Without it, risk scores cannot be computed."
    }
  },
  {
    "letter": "I",
    "term": "Inundation",
    "tag": "Data Source",
    "definitions": {
      "short": "The temporary flooding of land caused by overflow of water from rivers or heavy rainfall",
      "long": "Physical covering of land by floodwater. Measured by extent, depth, and duration. the driving factor varies from geography to geographies but primarily driven by riverine overflowing during monsoon."
    },
    "details": {
      "ids_drr": "Uses Satellite  imagery via Bhuvan to track spatial extent and duration of flooding across Districts/Subdistricts/Revenue circles each monsoon season.",
      "where_seen": "MODIS and Sentinel satellite flood maps, ASDMA FRIMS daily situation reports, BHUVAN portal, CWC flood bulletins",
      "why_it_matters": "Inundation extent is the primary input for flood hazard scores. Historical frequency data identifies which administrative unit faces repeated flooding."
    }
  },
  {
    "letter": "N",
    "term": "NDVI",
    "tag": "Data Source",
    "definitions": {
      "short": "Normalised Difference Vegetation Index — measures vegetation density from satellite imagery",
      "long": "Calculated from NIR and Red satellite bands. High values = dense vegetation (flood buffer); low values = barren/urban (faster runoff). Tracks seasonal land cover dynamics in the geographies"
    },
    "details": {
      "ids_drr": "Low NDVI areas (fallow land, chars, degraded forest) associated with higher surface runoff and flood susceptibility",
      "where_seen": "NASA Earth Data,USGS,DICRA",
      "why_it_matters": "Captures seasonal and multi-year land cover dynamics explaining year-to-year flood damage variation beyond rainfall alone."
    }
  },
  {
    "letter": "P",
    "term": "Procurement Data",
    "tag": "Data Source",
    "definitions": {
      "short": "Records of government contracts and tenders for an event-related goods, services, and works — used to assess efficiency and timeliness of public spending",
      "long": "Captures the full contracting cycle: what was procured, from whom, at what price, when awarded, and whether completed on time. Covers embankment works, relief supplies, early warning systems, and disaster equipment."
    },
    "details": {
      "ids_drr": "One of the first disaster risk models in India to incorporate procurement data. Uses assamtenders.gov.in and OCDS data to measure procurement timeliness, completion rates, and expenditure against budget.",
      "where_seen": "gePNIC portal, Finance Department budget documents, Open Contracting Partnership India datasets, CAG audit reports",
      "why_it_matters": "Budget allocation tells only part of the story. Late contracts, underperforming suppliers, or unspent funds mean allocations don't translate into protection"
    }
  },
  {
    "letter": "R",
    "term": "Resilience",
    "tag": "Conceptual",
    "definitions": {
      "short": "The ability of a community to absorb, adapt to, and recover from disaster impacts while maintaining essential functions",
      "long": "A resilient community can absorb shocks without catastrophic loss, adapt based on experience, and bounce back to pre-disaster or better conditions. Shaped by social cohesion, economic diversity, institutional strength, and resource access."
    },
    "details": {
      "ids_drr": "IDS-DRR proxies resilience through existing components: government response capacity (institutional), infrastructure access (physical), and low demographic deprivation (social). Improving any component increases resilience.",
      "where_seen": "Sendai Framework 2015-2030, UNDP Human Development Index, World Bank Resilience Index, ASDMA community resilience programme reports",
      "why_it_matters": "Resilience framing shifts DRR from reactive (responding) to proactive (building communities that can withstand and adapt). It is the long-term goal risk reduction investments work toward."
    }
  },
  {
    "letter": "R",
    "term": "Revenue Circle",
    "tag": "Administrative",
    "definitions": {
      "short": "The smallest administrative unit used for land revenue and governance in Assam, below sub-district level",
      "long": "Administrative subdivision for land records, revenue collection and local governance. IDS-DRR uses revenue circles as the primary unit of analysis for all risk scoring."
    },
    "details": {
      "ids_drr": "Computes all risk scores  hazard, vulnerability, exposure, and government response at the revenue circle level for the state of  Assam.",
      "where_seen": "Revenue department records, ASDMA damage reports, Census sub-district data, land record portal",
      "why_it_matters": "Revenue circle granularity identifies high-risk pockets within a district that district-level averages would mask."
    }
  },
  {
    "letter": "R",
    "term": "Risk Score",
    "tag": "Topographic Wetness Index",
    "definitions": {
      "short": "A composite index quantifying overall risk based on hazard, exposure, vulnerability, and government response",
      "long": "Aggregates multiple risk components into a single comparable value per geographic unit and hence enabling  prioritisation and tracking of change over time."
    },
    "details": {
      "ids_drr": "Computes a Comprehensive Risk Score for every revenue circle/district/subdistrict for a state  combining sub-scores for Flood Hazard, Exposure, Vulnerability, and Government Response.",
      "where_seen": "IDS-DRR dashboard, SDMA planning documents, district disaster management plans",
      "why_it_matters": "Translates complex multi-dimensional data into an actionable number for resource allocation and progress tracking."
    }
  },
  {
    "letter": "S",
    "term": "Slope",
    "tag": "Data Source",
    "definitions": {
      "short": "Rate of terrain elevation change derived from DEM — predictor of water flow speed and accumulation",
      "long": "Nearly flat slopes in floodplain cause slow-draining, long-duration inundation and  Steep slopes in hill districts generate rapid flash flood runoff."
    },
    "details": {
      "ids_drr": "In IDS-DRR Low-slope floodplain areas assigned higher flood hazard weights due to water accumulation characteristics.",
      "where_seen": "NASA Earth Data,USGS",
      "why_it_matters": "Structural reason some geographies experiences prolonged inundation  near-flat valley prevents rapid drainage after embankment breach or river overflow."
    }
  },
  {
    "letter": "V",
    "term": "Vulnerability",
    "tag": "Risk Component",
    "definitions": {
      "short": "The conditions that make people or assets more susceptible to harm from a hazard",
      "long": "Social, economic, physical, and institutional factors that increase likelihood of harm. Includes housing quality, health status, access to infrastructure, and governance strength."
    },
    "details": {
      "ids_drr": "Measures demographic vulnerability using WORLDPOP, Bharat Map and Antodaya  indicators: population density, sex ratio and household level data at the District/Subdistrict/Revenue Circle circle level.",
      "where_seen": "Census of India tables, NFHS health indicators, SECC deprivation data, SDMA damage reports disaggregated by population group",
      "why_it_matters": "Two areas with identical hazard and exposure can have very different outcomes depending on vulnerability"
    }
  }
];
