import { ComponentProps, FC } from 'react';
import {
  IconAnchor,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsCross,
  IconArrowUpRight,
  IconBarrierBlock,
  IconBellFilled,
  IconBrandFacebook,
  IconBrandLinkedin,
  IconBrandX,
  IconChartBar,
  IconChartInfographic,
  IconChevronDown,
  IconChevronLeft,
  IconChevronsLeft,
  IconChevronsRight,
  IconChevronUp,
  IconCircleChevronRight,
  IconDatabase,
  IconDatabaseCog,
  IconDatabasePlus,
  IconDatabaseSearch,
  IconDatabaseShare,
  IconDiamondsFilled,
  IconDots,
  IconDownload,
  IconExternalLink,
  IconFilter,
  IconHome,
  IconInfoCircleFilled,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLayoutSidebarRightCollapse,
  IconLink,
  IconListSearch,
  IconLoader,
  IconMap,
  IconMenu,
  IconMinus,
  IconRefresh,
  IconReport,
  IconReportSearch,
  IconSearch,
  IconShare,
  IconSquareRoundedArrowRight,
  IconSquareRoundedChevronLeftFilled,
  IconSwimming,
  IconSwipeDown,
  IconSwipeUp,
  IconTableAlias,
  IconUserCog,
  IconWorld,
  IconX,
} from '@tabler/icons-react';

type TablerIconComponent = FC<ComponentProps<typeof IconArrowLeft>>;

export const Icons: {
  [key: string]: TablerIconComponent;
} = {
  back: IconArrowLeft,
  logo: IconAnchor,
  dataset: IconDatabase,
  datasetSettings: IconDatabaseCog,
  addDataset: IconDatabasePlus,
  userSettings: IconUserCog,
  arrowRight: IconArrowRight,
  up: IconChevronUp,
  down: IconChevronDown,
  right: IconCircleChevronRight,
  left: IconChevronLeft,
  doubleLeft: IconChevronsLeft,
  doubleRight: IconChevronsRight,
  leftFilled: IconSquareRoundedChevronLeftFilled,
  search: IconSearch,
  IconSwimming: IconSwimming,
  notification: IconBellFilled,
  department: IconListSearch,
  scheme: IconReportSearch,
  cardLink: IconSquareRoundedArrowRight,
  info: IconInfoCircleFilled,
  share: IconShare,
  construction: IconBarrierBlock,
  link: IconLink,
  collapse: IconLayoutSidebarLeftCollapse,
  expand: IconLayoutSidebarLeftExpand,
  home: IconHome,
  overview: IconReport,
  explorer: IconChartInfographic,
  databaseShare: IconDatabaseShare,
  databaseSearch: IconDatabaseSearch,
  download: IconDownload,
  diamond: IconDiamondsFilled,
  externalLink: IconExternalLink,
  menu: IconMenu,
  cross: IconX,
  IconBrandX: IconBrandX,
  IconBrandFacebook: IconBrandFacebook,
  IconBrandLinkedin: IconBrandLinkedin,
  IconWorld: IconWorld,
  IconMap: IconMap,
  IconChartBar: IconChartBar,
  filter: IconFilter,
  IconTableAlias: IconTableAlias,
  IconDots: IconDots,
  IconArrowsCross: IconArrowsCross,
  IconMinus: IconMinus,
  IconRefresh: IconRefresh,
  IconSwipeUp: IconSwipeUp,
  IconSwipeDown: IconSwipeDown,
  loader: IconLoader,
  layoutSidebarRightCollapse: IconLayoutSidebarRightCollapse,
  IconArrowUpRight: IconArrowUpRight,
};

export default Icons;
