import fs from 'node:fs';
import path from 'node:path';

type CsvRow = Record<string, string>;

function parseCsv(text: string): CsvRow[] {
  const rows: string[][] = [];
  let currentField = '';
  let currentRow: string[] = [];
  let inQuotes = false;

  const pushField = () => {
    currentRow.push(currentField);
    currentField = '';
  };

  const pushRow = () => {
    // skip empty trailing lines
    if (currentRow.length === 1 && currentRow[0].trim() === '') {
      currentRow = [];
      return;
    }
    rows.push(currentRow);
    currentRow = [];
  };

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];

    if (ch === '"') {
      if (inQuotes && text[i + 1] === '"') {
        currentField += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (!inQuotes && ch === ',') {
      pushField();
      continue;
    }

    if (!inQuotes && (ch === '\n' || ch === '\r')) {
      // handle CRLF
      if (ch === '\r' && text[i + 1] === '\n') i++;
      pushField();
      pushRow();
      continue;
    }

    currentField += ch;
  }

  // final field/row
  pushField();
  if (currentRow.length > 0) pushRow();

  if (rows.length === 0) return [];
  const headers = rows[0].map((h) => h.trim());

  return rows.slice(1).map((r) => {
    const obj: CsvRow = {};
    for (let i = 0; i < headers.length; i++) {
      obj[headers[i]] = (r[i] ?? '').trim();
    }
    return obj;
  });
}

function toRelatedTerms(value: string): string[] {
  const raw = value.trim();
  if (!raw) return [];
  return raw
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean);
}

function buildDisasterDifferences(row: CsvRow) {
  const diffs: { disaster_type: string; difference: string }[] = [];
  for (let i = 0; i < 3; i++) {
    const t = row[`disaster_type_${i}`];
    const d = row[`difference_${i}`];
    if (!t && !d) continue;
    if (!t || !d) continue;
    diffs.push({ disaster_type: t, difference: d });
  }
  return diffs;
}

function nonEmpty(value: string | undefined | null): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function main() {
  const repoRoot = process.cwd();
  const csvPath = path.join(repoRoot, 'glossary', 'glossary.csv');
  const outPath = path.join(repoRoot, 'glossary', 'terms.generated.ts');

  const csvText = fs.readFileSync(csvPath, 'utf8');
  const rows = parseCsv(csvText);

  const items = rows
    .filter((r) => r.term && r.letter)
    .map((r) => {
      const letter = r.letter.toUpperCase();
      const term = r.term;
      const tag = (r.tag ?? '').trim();

      const policy = (r.policy ?? '').trim();
      const model = (r.model ?? '').trim();
      const contexts =
        nonEmpty(policy) || nonEmpty(model) ? { policy, model } : undefined;

      const disaster_differences = buildDisasterDifferences(r);
      const related_terms = toRelatedTerms(r.related_terms ?? '');

      const common_misinterpretation = (r.common_misinterpretation ?? '').trim();

      return {
        letter,
        term,
        ...(nonEmpty(tag) ? { tag } : {}),
        definitions: {
          short: (r.short ?? '').trim(),
          long: (r.long ?? '').trim(),
        },
        details: {
          ids_drr: (r.ids_drr ?? '').trim(),
          where_seen: (r.where_seen ?? '').trim(),
          why_it_matters: (r.why_it_matters ?? '').trim(),
        },
        ...(contexts ? { contexts } : {}),
        ...(disaster_differences.length > 0
          ? { disaster_differences }
          : {}),
        ...(related_terms.length > 0 ? { related_terms } : {}),
        ...(nonEmpty(common_misinterpretation)
          ? { common_misinterpretation }
          : {}),
      };
    })
    .sort((a, b) => {
      const byTerm = a.term.localeCompare(b.term, undefined, {
        sensitivity: 'base',
        numeric: true,
      });
      if (byTerm !== 0) return byTerm;

      const byLetter = a.letter.localeCompare(b.letter, undefined, {
        sensitivity: 'base',
      });
      if (byLetter !== 0) return byLetter;

      return (a.tag ?? '').localeCompare(b.tag ?? '', undefined, {
        sensitivity: 'base',
        numeric: true,
      });
    });

  const file = `/* eslint-disable */
// THIS FILE IS AUTO-GENERATED.
// Source: glossary/glossary.csv
// Generated by: scripts/generate-glossary.ts

import type { GlossaryItem } from './index';

export const GlossaryTermsSource: GlossaryItem[] = ${JSON.stringify(
    items,
    null,
    2
  )};
`;

  fs.writeFileSync(outPath, file, 'utf8');
}

main();
