name: Build Status

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
env:
  BACKEND_URL: ${{secrets.BACKEND_URL}}
  DATA_MANAGEMENT_LAYER_URL: ${{secrets.DATA_MANAGEMENT_LAYER_URL}}
  NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}
  NEXT_PUBLIC_DATA_MANAGEMENT_LAYER_URL: ${{secrets.NEXT_PUBLIC_DATA_MANAGEMENT_LAYER_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
      - uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - id: npm_ci
        run: npm ci --force
        continue-on-error: true
      - if: steps.npm_ci.outcome == 'failure'
        run: npm install --force
      - run: npm run lint
      - run: npm run knip
      - run: npm run type-check
      - run: npm run test
      - run: npm run build
      - if: steps.npm_ci.outcome == 'failure'
        run: |
          echo "::error::npm ci failed: Run `npm install --force` to update package-lock.json"
          exit 1
